apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: frontend-pod
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-cont
          image: paresh3292/python-jenkins:5
          ports:
            - conatinerPort: 80
