apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-nginx-pod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: nginx-pod
      labels:
        app: frontend
    spec:
      containers:
        - name: nginx-container
          image: nginx:stable-alpine
          ports:
            - containerPort: 80
